---

- hosts: windows
  gather_facts: no
  become: yes

  tasks:

  - name: Win_Ping
    win_ping:
    register: WinPingResult
    ignore_unreachable: yes

  - debug: var=WinPingResult.changed
    ignore_errors: yes

  - name: Printing errors
    debug:
      msg: "{{ WinPingResult.msg }}"
    run_once: yes
    changed_when: False
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansiblerunner
      minutes: : "*/10"
      job: ansible-pull -o -U 
